import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

const CustomEditor = dynamic(() => import('../components/CustomEditor'), {
  ssr: false
})

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>MarkDoc Editor PoC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {CustomEditor && <CustomEditor/>}
      </main>
    </div>
  )
}
